<template>
  <div class="global-techno">
    <h2>{{ $t('technos.titre') }}</h2>

    <div class="cadre">
      <h3>{{ $t('technos.front') }}</h3>
      <ul>
        <li>
          HTML
          <img
            src="../assets/logos/html.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          CSS / SCSS<img
            src="../assets/logos/css.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          /><img
            src="../assets/logos/scss.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          JavaScript / TypeScript<img
            src="../assets/logos/js.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          /><img
            src="../assets/logos/ts.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          React<img
            src="../assets/logos/react.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Angular<img
            src="../assets/logos/angular.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Vue<img
            src="../assets/logos/vue.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Astro<img
            src="../assets/logos/astro.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          React Native<img
            src="../assets/logos/react.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          PHP<img
            src="../assets/logos/php.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Laravel<img
            src="../assets/logos/laravel.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          JSF<img
            src="../assets/logos/jsf.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Primefaces<img
            src="../assets/logos/primefaces.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
      </ul>
    </div>

    <div class="cadre">
      <h3>{{ $t('technos.back') }}</h3>
      <ul>
        <li>
          Node.js<img
            src="../assets/logos/node.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Express<img
            src="../assets/logos/node.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Java<img
            src="../assets/logos/java.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Java Springboot<img
            src="../assets/logos/springboot.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          TypeORM<img
            src="../assets/logos/typeORM.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          GraphQL<img
            src="../assets/logos/graphQL.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          TypeGraphQL<img
            src="../assets/logos/typeGraphQL.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
      </ul>
    </div>

    <div class="cadre">
      <h3>{{ $t('technos.bdd') }}</h3>
      <ul>
        <li>
          SQL<img
            src="../assets/logos/sql.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          MySQLWorkbench<img
            src="../assets/logos/workbench.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          PgAdmin<img
            src="../assets/logos/pgadmin.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          HeidiSQL<img
            src="../assets/logos/heidiSQL.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          AWS<img
            src="../assets/logos/aws.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Google Cloud<img
            src="../assets/logos/googleCloud.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
      </ul>
    </div>

    <div class="cadre">
      <h3>{{ $t('technos.outils') }}</h3>
      <ul>
        <li>
          Git / Github / Gitlab / GitTortoise<img
            src="../assets/logos/git.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          /><img
            src="../assets/logos/github.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          /><img
            src="../assets/logos/gitlab.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
          <img
            src="../assets/logos/gitTortoise.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          jenkins<img
            src="../assets/logos/jenkins.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          SonarQube<img
            src="../assets/logos/sonar.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Jira<img
            src="../assets/logos/jira.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Mantis<img
            src="../assets/logos/mantis.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Figma<img
            src="../assets/logos/figma.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Docker<img
            src="../assets/logos/docker.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Talend<img
            src="../assets/logos/talend.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
      </ul>
    </div>

    <div class="cadre">
      <h3>{{ $t('technos.env') }}</h3>
      <ul>
        <li>
          VSCode<img
            src="../assets/logos/vscode.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          Eclipse<img
            src="../assets/logos/eclipse.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
      </ul>
    </div>

    <div class="cadre">
      <h3>{{ $t('technos.langues') }}</h3>
      <ul>
        <li>
          {{ $t('technos.fr')
          }}<img
            src="../assets/logos/fr.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
        <li>
          {{ $t('technos.en') }}
          <a
            href="https://drive.google.com/file/d/1oYb74V4GNN8yknTpi5SNoENS8QWXi7Y7/view?usp=sharing"
            target="_blank"
            class="ICI"
            aria-label="lien vers le document officiel pour le résultat du TOEIC"
            >(B2)</a
          >
          <img
            src="../assets/logos/en.png"
            alt=""
            role="presentation"
            aria-hidden="true"
            loading="lazy"
          />
        </li>
      </ul>
    </div>
  </div>
</template>
